title: Legos for the Blind
email: matshifrin@aol.com
url: "http://legosfortheblind.com/"
baseurl: "/legos-for-the-blind"
collections: 
  instructions:
    output: true
    permalink: /instructions/:path/
  links:
    output: true
    permalink: /links/:path/
sass:
  sass_dir: _sass
markdown: kramdown
include: ['_pages']
